# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
b=a.reshape(2,5)
print(b.tolist())


[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [31]:
import numpy as np
x=np.arange(10).reshape(2,5)
print(x)
y=np.ones(10).reshape(2,5)
print(y)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [39]:
import numpy as np
x=np.arange(10).reshape(2,5),np.ones(10).reshape(2,5)
print(x)
x[0:4]

(array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]]))


(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

## Question:7

### Create 5x5 an array and find the square of an array?

In [3]:
import numpy as np
x = np.random.random((5,5))
print(x,np.square(x))

[[0.01203642 0.36197729 0.77636823 0.86783658 0.60304532]
 [0.61992725 0.99232723 0.28332268 0.22604113 0.25340372]
 [0.65576827 0.28995534 0.61979607 0.60842439 0.22118197]
 [0.87842799 0.77993896 0.58394541 0.48199263 0.37573216]
 [0.89676864 0.88552016 0.23757847 0.23820923 0.83228839]] [[1.44875402e-04 1.31027555e-01 6.02747624e-01 7.53140338e-01
  3.63663656e-01]
 [3.84309794e-01 9.84713338e-01 8.02717425e-02 5.10945902e-02
  6.42134459e-02]
 [4.30032019e-01 8.40740985e-02 3.84147170e-01 3.70180241e-01
  4.89214647e-02]
 [7.71635731e-01 6.08304781e-01 3.40992237e-01 2.32316891e-01
  1.41174656e-01]
 [8.04193986e-01 7.84145958e-01 5.64435288e-02 5.67436380e-02
  6.92703966e-01]]


## Question:8

### Create 5x6 an array and find the mean?

In [5]:
import numpy as np
x = np.random.random((5,6))
print(x)
np.mean(x)

[[0.79562023 0.04735201 0.45975495 0.24905558 0.41842384 0.98683269]
 [0.6779186  0.65327625 0.05652671 0.75874444 0.8305872  0.36727513]
 [0.43360366 0.2693688  0.01835712 0.57109978 0.35048275 0.14543592]
 [0.16762379 0.84786573 0.87485272 0.30443582 0.32330798 0.08431626]
 [0.801615   0.3156994  0.18495361 0.45549525 0.41874938 0.86425911]]


0.4577629895055371

## Question:9

### Find the standard deviation of the previous array in Q8?

In [6]:
import numpy as np
x = np.random.random((5,6))
print(x)
np.std(x)

[[0.40698558 0.75970054 0.49797864 0.5839416  0.65567198 0.4152267 ]
 [0.37864309 0.99718381 0.15784289 0.51360431 0.05732558 0.80298809]
 [0.68004806 0.64176932 0.47337661 0.49854614 0.229349   0.64180511]
 [0.32175193 0.29517768 0.83382801 0.11419688 0.70595357 0.45775394]
 [0.21588171 0.25938847 0.34207674 0.04111037 0.31753049 0.98253978]]


0.25359156108416053

## Question:10

### Find the median of the previous array in Q8?

In [8]:
import numpy as np
x = np.random.random((5,6))
print(x)
np.median(x)

[[0.0103518  0.01851923 0.73445327 0.2382243  0.62173845 0.6073922 ]
 [0.48849961 0.33162102 0.56149154 0.97113838 0.65625159 0.19965483]
 [0.65380685 0.44347335 0.62823342 0.23032155 0.58449954 0.77967839]
 [0.82355131 0.5870432  0.13263644 0.15048895 0.59910912 0.67807761]
 [0.231823   0.29136165 0.82962231 0.1060707  0.81835553 0.53018193]]


0.572995538132666

## Question:11

### Find the transpose of the previous array in Q8?

In [9]:
import numpy as np
x = np.random.random((5,6))
print(x)
np.transpose(x)

[[0.90901428 0.25469322 0.36427013 0.61687312 0.22081148 0.23970231]
 [0.31179247 0.53173072 0.04398404 0.32564749 0.29641928 0.00744235]
 [0.51851527 0.47782475 0.68250348 0.02713447 0.21537929 0.74215743]
 [0.97048431 0.13303341 0.47879402 0.47752475 0.31162692 0.77043237]
 [0.31188518 0.35005215 0.08878185 0.20221608 0.49022939 0.81339558]]


array([[0.90901428, 0.31179247, 0.51851527, 0.97048431, 0.31188518],
       [0.25469322, 0.53173072, 0.47782475, 0.13303341, 0.35005215],
       [0.36427013, 0.04398404, 0.68250348, 0.47879402, 0.08878185],
       [0.61687312, 0.32564749, 0.02713447, 0.47752475, 0.20221608],
       [0.22081148, 0.29641928, 0.21537929, 0.31162692, 0.49022939],
       [0.23970231, 0.00744235, 0.74215743, 0.77043237, 0.81339558]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [10]:
import numpy as np 
n_array = np.array([[55, 25, 15, 41], 
                    [30, 44, 2, 54], 
                    [11, 45, 77, 11], 
                    [11, 212, 4, 20]]) 
   
print(n_array) 
trace = np.trace(n_array) 
print(trace) 

[[ 55  25  15  41]
 [ 30  44   2  54]
 [ 11  45  77  11]
 [ 11 212   4  20]]
196


## Question:13

### Find the determinant of the previous array in Q12?

In [12]:
import numpy as np 
n_array = np.array([[55, 25, 15, 41], 
                    [30, 44, 2, 54], 
                    [11, 45, 77, 11], 
                    [11, 212, 4, 20]]) 
   
print(n_array)
print(np.linalg.det(n_array))

[[ 55  25  15  41]
 [ 30  44   2  54]
 [ 11  45  77  11]
 [ 11 212   4  20]]
-25166735.999999996


## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
import numpy as np 
arr = [20, 2, 7, 1, 34]
print(arr) 
print(np.percentile(arr, 5))
print(np.percentile(arr, 95))

[20, 2, 7, 1, 34]
1.2000000000000002
31.2


## Question:15

### How to find if a given array has any null values?

In [15]:
 import numpy as np

b = np.array([[4, np.inf],[np.nan, -np.inf]])

np.isnan(b)

array([[False, False],
       [ True, False]])